version: "3.8"

services:
  app:
    build: .
    container_name: eventmanagement_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/seat_booking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: harsh0033
      SPRING_MAIL_USERNAME: dcodeionlab@gmail.com
      SPRING_MAIL_PASSWORD: xxwv pvvc asas weqr
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: harsh0033
      MYSQL_DATABASE: seat_booking
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
